sources:
  - name: Employees
    handler:
      mysql:
         host: "{env.DB_HOST}"
         port: 3307
         user: "{env.DB_USER}"
         password: "{env.DB_PASSWORD}"
         database: "{env.DB_DATABASE}"