sources:
  - name: Meeware
    handler:
      mysql:
        # You can use environment variables like
        host: "meeovimariadb.ctxiztlmalra.us-east-1.rds.amazonaws.com"
        port: 3306
        user: "bastianhilton"
        password: "Libraxus1986"
        database: "meeware"
        #host: meeovicms.com
        #port: 3306
        #user: admin_shop812
        #password: 4p.SYEJ!84
        #database: admin_shop812

  #- name: Meeware
  #  handler:
  #    openapi:
  #      source: '{env.REST_URL}/store-api/_info/openapi3.json'
  #      endpoint: '{env.REST_URL}/store-api/'
  #      operationHeaders:
  #        Authorization-Header: '{env.REST_HEADER}'
  #        Authorization-Cookie: Bearer {env.REST_API_KEY}
 
# You can provide a custom fetch function to override the default fetch function
serve:
  playground: true
