sources:
  - name: CommerceUI
    handler:
      jsonSchema:
        endpoint: https://cms.meeovicms.com/endpoint-path/
        operations:
          - type: Query
            field: users
            path: /users
            method: GET
            responseSchema: ./json-schemas/users.json