sources:
  - name: eCommerce
    handler:
      openapi:
        source: http://153.92.1.142:8020/api/
        operationHeaders:
          Authorization: Bearer {sw-access-key['SWSCBVFHCNZQR2R1YKYXAFBYAW']}

serve:
  playground: true
  playgroundTitle: 'Meeovi Graphql'