sources:
  - name: Meeware
    handler:
      mysql:
        # You can use environment variables like
        # host: "{env.MYSQL_HOST}"
        # port: "{env.MYSQL_PORT}"
        # user: "{env.MYSQL_USER}"
        # password: "{env.MYSQL_PASSWORD}"
        # database: "{env.MYSQL_DATABASE}"
        host: meeovicms.com
        port: 3306
        user: admin_shop812
        password: 4p.SYEJ!84
        database: admin_shop812
serve:
  playground: true
