query activeChannel{
    activeChannel{
        id
        createdAt
        updatedAt
        code
        token
        defaultTaxZone{
            id
            createdAt
            updatedAt
            name
            members{
                id
                createdAt
                updatedAt
                languageCode
                code
                type
                name
                enabled
                parent{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    code
                    type
                    name
                    enabled
                    parent{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        code
                        type
                        name
                        enabled
                        parentId
                    }
                    parentId
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                }
                parentId
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                }
            }
            customFields
        }
        defaultShippingZone{
            id
            createdAt
            updatedAt
            name
            members{
                id
                createdAt
                updatedAt
                languageCode
                code
                type
                name
                enabled
                parentId
            }
            customFields
        }
        defaultLanguageCode
        availableLanguageCodes
        defaultCurrencyCode
        availableCurrencyCodes
        trackInventory
        outOfStockThreshold
        pricesIncludeTax
        seller{
            id
            createdAt
            updatedAt
            name
            customFields
        }
        customFields
    }
}