query NewQuery {
  charts {
    nodes {
      chartFields {
        name
        image {
          node {
            sourceUrl
          }
        }
        products {
          nodes {
            id
            ... on SimpleProduct {
              id
              name
              price
            }
          }
        }
        color
      }
      id
      date
    }
  }
}