query collections{
    collections(options: {topLevelOnly: true, filter: {name: {notEq: "Outlets"}}})
        items{
            id
            createdAt
            updatedAt
            languageCode
            name
            slug
            breadcrumbs{
                id
                name
                slug
            }
            position
            description
            featuredAsset{
                id
                createdAt
                updatedAt
                name
                type
                fileSize
                mimeType
                width
                height
                source
                preview
                focalPoint{
                    x
                    y
                }
                tags{
                    id
                    createdAt
                    updatedAt
                    value
                }
                customFields
            }
            assets{
                id
                createdAt
                updatedAt
                name
                type
                fileSize
                mimeType
                width
                height
                source
                preview
                focalPoint{
                    x
                    y
                }
                tags{
                    id
                    createdAt
                    updatedAt
                    value
                }
                customFields
            }
            parent{
                id
                createdAt
                updatedAt
                languageCode
                name
                slug
                breadcrumbs{
                    id
                    name
                    slug
                }
                position
                description
                featuredAsset{
                    id
                    createdAt
                    updatedAt
                    name
                    type
                    fileSize
                    mimeType
                    width
                    height
                    source
                    preview
                    customFields
                }
                assets{
                    id
                    createdAt
                    updatedAt
                    name
                    type
                    fileSize
                    mimeType
                    width
                    height
                    source
                    preview
                    customFields
                }
                customFields
            }
            children{
                id
                createdAt
                updatedAt
                languageCode
                name
                slug
                breadcrumbs{
                    id
                    name
                    slug
                }
                position
                description
                featuredAsset{
                    id
                    createdAt
                    updatedAt
                    name
                    type
                    fileSize
                    mimeType
                    width
                    height
                    source
                    preview
                    customFields
                }
                assets{
                    id
                    createdAt
                    updatedAt
                    name
                    type
                    fileSize
                    mimeType
                    width
                    height
                    source
                    preview
                    customFields
                }
                parent{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    position
                    description
                    parentId
                    customFields
                }
                children{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    position
                    description
                    parentId
                    filters{
                        code
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        description
                    }
                    productVariants{
                        totalItems
                    }
                    customFields
                }
                customFields
            }
            filters{
                code
                args{
                    name
                    value
                }
            }
            translations{
                id
                createdAt
                updatedAt
                languageCode
                name
                slug
                description
            }
            productVariants{
                items{
                    id
                    product{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        description
                        enabled
                        customFields
                    }
                    productId
                    createdAt
                    updatedAt
                    languageCode
                    sku
                    name
                    price
                    currencyCode
                    priceWithTax
                    stockLevel
                    taxRateApplied{
                        id
                        createdAt
                        updatedAt
                        name
                        enabled
                        value
                        customFields
                    }
                    taxCategory{
                        id
                        createdAt
                        updatedAt
                        name
                        isDefault
                        customFields
                    }
                    options{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        code
                        name
                        groupId
                        customFields
                    }
                    facetValues{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        facetId
                        name
                        code
                        customFields
                    }
                    customFields
                }
                totalItems
            }
            customFields
        }
        totalItems
    }