query product($options: ProductVariantListOptions, $options1: ProductVariantListOptions, $options2: CustomerListOptions, $id: ID, $slug: String){
    product(id: $id, slug: $slug){
        id
        createdAt
        updatedAt
        languageCode
        name
        slug
        description
        enabled
        featuredAsset{
            id
            createdAt
            updatedAt
            name
            type
            fileSize
            mimeType
            width
            height
            source
            preview
            focalPoint{
                x
                y
            }
            tags{
                id
                createdAt
                updatedAt
                value
            }
            customFields
        }
        assets{
            id
            createdAt
            updatedAt
            name
            type
            fileSize
            mimeType
            width
            height
            source
            preview
            focalPoint{
                x
                y
            }
            tags{
                id
                createdAt
                updatedAt
                value
            }
            customFields
        }
        variants{
            id
            product{
                id
                createdAt
                updatedAt
                languageCode
                name
                slug
                description
                enabled
                variantList(options: $options){
                    items{
                        id
                        productId
                        createdAt
                        updatedAt
                        languageCode
                        sku
                        name
                        price
                        currencyCode
                        priceWithTax
                        stockLevel
                        customFields
                    }
                    totalItems
                }
                optionGroups{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    code
                    name
                    options{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        code
                        name
                        groupId
                        customFields
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                    customFields
                }
                facetValues{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    facet{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        code
                        customFields
                    }
                    facetId
                    name
                    code
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                    customFields
                }
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    description
                }
                collections{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    breadcrumbs{
                        id
                        name
                        slug
                    }
                    position
                    description
                    featuredAsset{
                        id
                        createdAt
                        updatedAt
                        name
                        type
                        fileSize
                        mimeType
                        width
                        height
                        source
                        preview
                        customFields
                    }
                    assets{
                        id
                        createdAt
                        updatedAt
                        name
                        type
                        fileSize
                        mimeType
                        width
                        height
                        source
                        preview
                        customFields
                    }
                    parent{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        position
                        description
                        parentId
                        customFields
                    }
                    children{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        position
                        description
                        customFields
                    }
                    filters{
                        code
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        description
                    }
                    productVariants(options: $options1){
                        totalItems
                    }
                    customFields
                }
                customFields
            }
            productId
            createdAt
            updatedAt
            languageCode
            sku
            name
            featuredAsset{
                id
                createdAt
                updatedAt
                name
                type
                fileSize
                mimeType
                width
                height
                source
                preview
                customFields
            }
            assets{
                id
                createdAt
                updatedAt
                name
                type
                fileSize
                mimeType
                width
                height
                source
                preview
                customFields
            }
            price
            currencyCode
            priceWithTax
            stockLevel
            taxRateApplied{
                id
                createdAt
                updatedAt
                name
                enabled
                value
                category{
                    id
                    createdAt
                    updatedAt
                    name
                    isDefault
                    customFields
                }
                zone{
                    id
                    createdAt
                    updatedAt
                    name
                    members{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        code
                        type
                        name
                        enabled
                        parentId
                    }
                    customFields
                }
                customerGroup{
                    id
                    createdAt
                    updatedAt
                    name
                    customers(options: $options2){
                        totalItems
                    }
                    customFields
                }
                customFields
            }
            taxCategory{
                id
                createdAt
                updatedAt
                name
                isDefault
                customFields
            }
            options{
                id
                createdAt
                updatedAt
                languageCode
                code
                name
                groupId
                group{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    code
                    name
                    options{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        code
                        name
                        groupId
                        customFields
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                    customFields
                }
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                }
                customFields
            }
            facetValues{
                id
                createdAt
                updatedAt
                languageCode
                facetId
                name
                code
                customFields
            }
            translations{
                id
                createdAt
                updatedAt
                languageCode
                name
            }
            customFields
        }
        customFields
    }
}