query search($options: FacetValueListOptions, $options1: ProductVariantListOptions, $options2: ProductVariantListOptions, $options3: ProductVariantListOptions, $input: SearchInput!){
    search(input: $input){
        items{
            sku
            slug
            productId
            productName
            productAsset{
                id
                preview
                focalPoint{
                    x
                    y
                }
            }
            productVariantId
            productVariantName
            productVariantAsset{
                id
                preview
                focalPoint{
                    x
                    y
                }
            }
            price{
                __typename
                ... on PriceRange {
                    min
                    max
                }
                ... on SinglePrice {
                    value
                }
            }
            priceWithTax{
                __typename
                ... on PriceRange {
                    min
                    max
                }
                ... on SinglePrice {
                    value
                }
            }
            currencyCode
            description
            facetIds
            facetValueIds
            collectionIds
            score
            inStock
        }
        totalItems
        facetValues{
            facetValue{
                id
                createdAt
                updatedAt
                languageCode
                facet{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    code
                    values{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        facetId
                        name
                        code
                        customFields
                    }
                    valueList(options: $options){
                        totalItems
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                    customFields
                }
                facetId
                name
                code
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                }
                customFields
            }
            count
        }
        collections{
            collection{
                id
                createdAt
                updatedAt
                languageCode
                name
                slug
                breadcrumbs{
                    id
                    name
                    slug
                }
                position
                description
                featuredAsset{
                    id
                    createdAt
                    updatedAt
                    name
                    type
                    fileSize
                    mimeType
                    width
                    height
                    source
                    preview
                    focalPoint{
                        x
                        y
                    }
                    tags{
                        id
                        createdAt
                        updatedAt
                        value
                    }
                    customFields
                }
                assets{
                    id
                    createdAt
                    updatedAt
                    name
                    type
                    fileSize
                    mimeType
                    width
                    height
                    source
                    preview
                    focalPoint{
                        x
                        y
                    }
                    tags{
                        id
                        createdAt
                        updatedAt
                        value
                    }
                    customFields
                }
                parent{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    breadcrumbs{
                        id
                        name
                        slug
                    }
                    position
                    description
                    featuredAsset{
                        id
                        createdAt
                        updatedAt
                        name
                        type
                        fileSize
                        mimeType
                        width
                        height
                        source
                        preview
                        customFields
                    }
                    assets{
                        id
                        createdAt
                        updatedAt
                        name
                        type
                        fileSize
                        mimeType
                        width
                        height
                        source
                        preview
                        customFields
                    }
                    parent{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        position
                        description
                        parentId
                        customFields
                    }
                    parentId
                    children{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        position
                        description
                        parentId
                        customFields
                    }
                    filters{
                        code
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        description
                    }
                    productVariants(options: $options1){
                        totalItems
                    }
                    customFields
                }
                parentId
                children{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    breadcrumbs{
                        id
                        name
                        slug
                    }
                    position
                    description
                    featuredAsset{
                        id
                        createdAt
                        updatedAt
                        name
                        type
                        fileSize
                        mimeType
                        width
                        height
                        source
                        preview
                        customFields
                    }
                    assets{
                        id
                        createdAt
                        updatedAt
                        name
                        type
                        fileSize
                        mimeType
                        width
                        height
                        source
                        preview
                        customFields
                    }
                    parent{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        position
                        description
                        parentId
                        customFields
                    }
                    parentId
                    children{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        position
                        description
                        parentId
                        customFields
                    }
                    filters{
                        code
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        slug
                        description
                    }
                    productVariants(options: $options2){
                        totalItems
                    }
                    customFields
                }
                filters{
                    code
                    args{
                        name
                        value
                    }
                }
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    slug
                    description
                }
                productVariants(options: $options3){
                    items{
                        id
                        productId
                        createdAt
                        updatedAt
                        languageCode
                        sku
                        name
                        price
                        currencyCode
                        priceWithTax
                        stockLevel
                        customFields
                    }
                    totalItems
                }
                customFields
            }
            count
        }
    }
}