query activity($format: ContentFieldFormatEnum, $format1: ContentFieldFormatEnum, $format2: ContentFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $where: ActivityToActivityConnectionWhereArgs, $format3: ContentFieldFormatEnum, $size: Int, $forceDefault: Boolean, $rating: AvatarRatingEnum, $format4: ContentFieldFormatEnum, $format5: ContentFieldFormatEnum, $format6: ContentFieldFormatEnum, $format7: ContentFieldFormatEnum, $first1: Int, $last1: Int, $after1: String, $before1: String, $where1: ActivityToActivityConnectionWhereArgs, $format8: ContentFieldFormatEnum, $format9: ContentFieldFormatEnum, $format10: ContentFieldFormatEnum, $id: ID!, $idType: ActivityIdTypeEnum){
    activity(id: $id, idType: $idType){
        comments(first: $first1, last: $last1, after: $after1, before: $before1, where: $where1){
            edges{
                cursor
                node{
                    component
                    content(format: $format)
                    creator{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format1)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                    databaseId
                    date
                    dateGmt
                    hidden
                    id
                    isComment
                    isContentNode
                    isFavorited
                    isFrontPage
                    isPostsPage
                    isTermNode
                    parent{
                        component
                        content(format: $format2)
                        databaseId
                        date
                        dateGmt
                        hidden
                        id
                        isComment
                        isContentNode
                        isFavorited
                        isFrontPage
                        isPostsPage
                        isTermNode
                        parentDatabaseId
                        parentId
                        primaryItemId
                        secondaryItemId
                        status
                        title
                        type
                        uri
                    }
                    parentDatabaseId
                    parentId
                    primaryItemId
                    secondaryItemId
                    status
                    title
                    type
                    uri
                }
            }
            nodes{
                comments(first: $first, last: $last, after: $after, before: $before, where: $where){
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                component
                content(format: $format3)
                creator{
                    attachmentAvatar{
                        full
                        thumb
                    }
                    attachmentCover{
                        full
                        thumb
                    }
                    avatar(size: $size, forceDefault: $forceDefault, rating: $rating){
                        default
                        extraAttr
                        forceDefault
                        foundAvatar
                        height
                        isRestricted
                        rating
                        scheme
                        size
                        url
                        width
                    }
                    capKey
                    capabilities
                    databaseId
                    description
                    email
                    extraCapabilities
                    firstName
                    id
                    isComment
                    isContentNode
                    isFrontPage
                    isPostsPage
                    isRestricted
                    isTermNode
                    lastName
                    latestUpdate(format: $format4)
                    link
                    locale
                    memberTypes
                    mentionName
                    name
                    nicename
                    nickname
                    registeredDate
                    shouldShowAdminToolbar
                    slug
                    totalFriendCount
                    totalMessagesUnreadCount
                    uri
                    url
                    username
                }
                databaseId
                date
                dateGmt
                hidden
                id
                isComment
                isContentNode
                isFavorited
                isFrontPage
                isPostsPage
                isTermNode
                parent{
                    component
                    content(format: $format5)
                    creator{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format6)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                    databaseId
                    date
                    dateGmt
                    hidden
                    id
                    isComment
                    isContentNode
                    isFavorited
                    isFrontPage
                    isPostsPage
                    isTermNode
                    parent{
                        component
                        content(format: $format7)
                        databaseId
                        date
                        dateGmt
                        hidden
                        id
                        isComment
                        isContentNode
                        isFavorited
                        isFrontPage
                        isPostsPage
                        isTermNode
                        parentDatabaseId
                        parentId
                        primaryItemId
                        secondaryItemId
                        status
                        title
                        type
                        uri
                    }
                    parentDatabaseId
                    parentId
                    primaryItemId
                    secondaryItemId
                    status
                    title
                    type
                    uri
                }
                parentDatabaseId
                parentId
                primaryItemId
                secondaryItemId
                status
                title
                type
                uri
            }
        }
        component
        content(format: $format8)
        creator{
            capKey
            capabilities
            databaseId
            description
            email
            extraCapabilities
            firstName
            id
            isComment
            isContentNode
            isFrontPage
            isPostsPage
            isRestricted
            isTermNode
            lastName
            latestUpdate(format: $format9)
            link
            locale
            memberTypes
            mentionName
            name
            nicename
            nickname
            registeredDate
            shouldShowAdminToolbar
            slug
            totalFriendCount
            totalMessagesUnreadCount
            uri
            url
            username
        }
        databaseId
        date
        dateGmt
        hidden
        id
        isComment
        isContentNode
        isFavorited
        isFrontPage
        isPostsPage
        isTermNode
        parent{
            component
            content(format: $format10)
            databaseId
            date
            dateGmt
            hidden
            id
            isComment
            isContentNode
            isFavorited
            isFrontPage
            isPostsPage
            isTermNode
            parentDatabaseId
            parentId
            primaryItemId
            secondaryItemId
            status
            title
            type
            uri
        }
        parentDatabaseId
        parentId
        primaryItemId
        secondaryItemId
        status
        title
        type
        uri
    }
}