query activities($format: ContentFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $where: ActivityToActivityConnectionWhereArgs, $format1: ContentFieldFormatEnum, $size: Int, $forceDefault: Boolean, $rating: AvatarRatingEnum, $format2: ContentFieldFormatEnum, $format3: ContentFieldFormatEnum, $format4: ContentFieldFormatEnum, $format5: ContentFieldFormatEnum, $format6: ContentFieldFormatEnum, $format7: ContentFieldFormatEnum, $format8: ContentFieldFormatEnum, $first1: Int, $last1: Int, $after1: String, $before1: String, $where1: RootQueryToActivityConnectionWhereArgs){
    activities(first: $first1, last: $last1, after: $after1, before: $before1, where: $where1){
        edges{
            cursor
            node{
                comments(first: $first, last: $last, after: $after, before: $before, where: $where){
                    edges{
                        cursor
                    }
                    nodes{
                        component
                        content(format: $format)
                        databaseId
                        date
                        dateGmt
                        hidden
                        id
                        isComment
                        isContentNode
                        isFavorited
                        isFrontPage
                        isPostsPage
                        isTermNode
                        parentDatabaseId
                        parentId
                        primaryItemId
                        secondaryItemId
                        status
                        title
                        type
                        uri
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                component
                content(format: $format1)
                creator{
                    attachmentAvatar{
                        full
                        thumb
                    }
                    attachmentCover{
                        full
                        thumb
                    }
                    avatar(size: $size, forceDefault: $forceDefault, rating: $rating){
                        default
                        extraAttr
                        forceDefault
                        foundAvatar
                        height
                        isRestricted
                        rating
                        scheme
                        size
                        url
                        width
                    }
                    capKey
                    capabilities
                    databaseId
                    description
                    email
                    extraCapabilities
                    firstName
                    id
                    isComment
                    isContentNode
                    isFrontPage
                    isPostsPage
                    isRestricted
                    isTermNode
                    lastName
                    latestUpdate(format: $format2)
                    link
                    locale
                    memberTypes
                    mentionName
                    name
                    nicename
                    nickname
                    registeredDate
                    shouldShowAdminToolbar
                    slug
                    totalFriendCount
                    totalMessagesUnreadCount
                    uri
                    url
                    username
                }
                databaseId
                date
                dateGmt
                hidden
                id
                isComment
                isContentNode
                isFavorited
                isFrontPage
                isPostsPage
                isTermNode
                parent{
                    component
                    content(format: $format3)
                    creator{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format4)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                    databaseId
                    date
                    dateGmt
                    hidden
                    id
                    isComment
                    isContentNode
                    isFavorited
                    isFrontPage
                    isPostsPage
                    isTermNode
                    parent{
                        component
                        content(format: $format5)
                        databaseId
                        date
                        dateGmt
                        hidden
                        id
                        isComment
                        isContentNode
                        isFavorited
                        isFrontPage
                        isPostsPage
                        isTermNode
                        parentDatabaseId
                        parentId
                        primaryItemId
                        secondaryItemId
                        status
                        title
                        type
                        uri
                    }
                    parentDatabaseId
                    parentId
                    primaryItemId
                    secondaryItemId
                    status
                    title
                    type
                    uri
                }
                parentDatabaseId
                parentId
                primaryItemId
                secondaryItemId
                status
                title
                type
                uri
            }
        }
        nodes{
            component
            content(format: $format6)
            creator{
                capKey
                capabilities
                databaseId
                description
                email
                extraCapabilities
                firstName
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isRestricted
                isTermNode
                lastName
                latestUpdate(format: $format7)
                link
                locale
                memberTypes
                mentionName
                name
                nicename
                nickname
                registeredDate
                shouldShowAdminToolbar
                slug
                totalFriendCount
                totalMessagesUnreadCount
                uri
                url
                username
            }
            databaseId
            date
            dateGmt
            hidden
            id
            isComment
            isContentNode
            isFavorited
            isFrontPage
            isPostsPage
            isTermNode
            parent{
                component
                content(format: $format8)
                databaseId
                date
                dateGmt
                hidden
                id
                isComment
                isContentNode
                isFavorited
                isFrontPage
                isPostsPage
                isTermNode
                parentDatabaseId
                parentId
                primaryItemId
                secondaryItemId
                status
                title
                type
                uri
            }
            parentDatabaseId
            parentId
            primaryItemId
            secondaryItemId
            status
            title
            type
            uri
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}