query availableCountries{
    availableCountries{
        id
        createdAt
        updatedAt
        languageCode
        code
        type
        name
        enabled
        parent{
            id
            createdAt
            updatedAt
            languageCode
            code
            type
            name
            enabled
            parent{
                id
                createdAt
                updatedAt
                languageCode
                code
                type
                name
                enabled
                parentId
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                }
            }
            parentId
        }
        parentId
        translations{
            id
            createdAt
            updatedAt
            languageCode
            name
        }
        customFields
    }
}