query comments($format: PostObjectFieldFormatEnum, $format1: PostObjectFieldFormatEnum, $where: CommentToParentCommentConnectionWhereArgs, $format2: PostObjectFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $where1: CommentToCommentConnectionWhereArgs, $format3: PostObjectFieldFormatEnum, $where2: CommentToParentCommentConnectionWhereArgs, $first1: Int, $last1: Int, $after1: String, $before1: String, $where3: RootQueryToCommentConnectionWhereArgs){
    comments(first: $first1, last: $last1, after: $after1, before: $before1, where: $where3){
        edges{
            cursor
            node{
                agent
                author{
                    cursor
                    email
                    ipAddress
                    name
                    node{
                        databaseId
                        email
                        id
                        isRestricted
                        name
                        url
                    }
                    url
                }
                commentedOn{
                    cursor
                    node{
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        guid
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        modified
                        modifiedGmt
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        uri
                    }
                }
                content(format: $format)
                databaseId
                date
                dateGmt
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isRestricted
                isTermNode
                karma
                link
                parent(where: $where){
                    cursor
                    node{
                        agent
                        content(format: $format1)
                        databaseId
                        date
                        dateGmt
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        karma
                        link
                        parentDatabaseId
                        parentId
                        status
                        type
                        uri
                    }
                }
                parentDatabaseId
                parentId
                replies(first: $first, last: $last, after: $after, before: $before, where: $where1){
                    edges{
                        cursor
                    }
                    nodes{
                        agent
                        content(format: $format2)
                        databaseId
                        date
                        dateGmt
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        karma
                        link
                        parentDatabaseId
                        parentId
                        status
                        type
                        uri
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                status
                type
                uri
            }
        }
        nodes{
            agent
            author{
                cursor
                email
                ipAddress
                name
                url
            }
            commentedOn{
                cursor
            }
            content(format: $format3)
            databaseId
            date
            dateGmt
            id
            isComment
            isContentNode
            isFrontPage
            isPostsPage
            isRestricted
            isTermNode
            karma
            link
            parent(where: $where2){
                cursor
            }
            parentDatabaseId
            parentId
            status
            type
            uri
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}