query comment($format: ContentFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $first1: Int, $last1: Int, $after1: String, $before1: String, $format1: ContentFieldFormatEnum, $format2: PostObjectFieldFormatEnum, $format3: PostObjectFieldFormatEnum, $where: CommentToParentCommentConnectionWhereArgs, $format4: PostObjectFieldFormatEnum, $first2: Int, $last2: Int, $after2: String, $before2: String, $where1: CommentToCommentConnectionWhereArgs, $where2: CommentToParentCommentConnectionWhereArgs, $id: ID!, $idType: CommentNodeIdTypeEnum){
    comment(id: $id, idType: $idType){
        agent
        author{
            cursor
            email
            ipAddress
            name
            node{
                avatar{
                    default
                    extraAttr
                    forceDefault
                    foundAvatar
                    height
                    isRestricted
                    rating
                    scheme
                    size
                    url
                    width
                }
                databaseId
                email
                id
                isRestricted
                name
                url
            }
            url
        }
        commentedOn{
            cursor
            node{
                contentType{
                    cursor
                    node{
                        canExport
                        deleteWithUser
                        description
                        excludeFromSearch
                        graphqlPluralName
                        graphqlSingleName
                        hasArchive
                        hierarchical
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        label
                        menuIcon
                        menuPosition
                        name
                        public
                        publiclyQueryable
                        restBase
                        restControllerClass
                        showInAdminBar
                        showInGraphql
                        showInMenu
                        showInNavMenus
                        showInRest
                        showUi
                        uri
                    }
                }
                contentTypeName
                databaseId
                date
                dateGmt
                desiredSlug
                editingLockedBy{
                    cursor
                    lockTimestamp
                    node{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                }
                enclosure
                enqueuedScripts(first: $first, last: $last, after: $after, before: $before){
                    edges{
                        cursor
                    }
                    nodes{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                enqueuedStylesheets(first: $first1, last: $last1, after: $after1, before: $before1){
                    edges{
                        cursor
                    }
                    nodes{
                        after
                        before
                        conditional
                        group
                        handle
                        id
                        isRtl
                        media
                        path
                        rel
                        src
                        suffix
                        title
                        version
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                guid
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isPreview
                isRestricted
                isTermNode
                lastEditedBy{
                    cursor
                    node{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format1)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                }
                link
                modified
                modifiedGmt
                previewRevisionDatabaseId
                previewRevisionId
                slug
                status
                template{
                    templateName
                }
                uri
            }
        }
        content(format: $format2)
        databaseId
        date
        dateGmt
        id
        isComment
        isContentNode
        isFrontPage
        isPostsPage
        isRestricted
        isTermNode
        karma
        link
        parent(where: $where2){
            cursor
            node{
                agent
                author{
                    cursor
                    email
                    ipAddress
                    name
                    url
                }
                commentedOn{
                    cursor
                }
                content(format: $format3)
                databaseId
                date
                dateGmt
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isRestricted
                isTermNode
                karma
                link
                parent(where: $where){
                    cursor
                }
                parentDatabaseId
                parentId
                replies(first: $first2, last: $last2, after: $after2, before: $before2, where: $where1){
                    edges{
                        cursor
                    }
                    nodes{
                        agent
                        content(format: $format4)
                        databaseId
                        date
                        dateGmt
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        karma
                        link
                        parentDatabaseId
                        parentId
                        status
                        type
                        uri
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                status
                type
                uri
            }
        }
        parentDatabaseId
        parentId
        status
        type
        uri
    }
}