query facets($options: FacetValueListOptions, $options1: FacetValueListOptions, $options2: FacetListOptions){
    facets(options: $options2){
        items{
            id
            createdAt
            updatedAt
            languageCode
            name
            code
            values{
                id
                createdAt
                updatedAt
                languageCode
                facet{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                    code
                    values{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        facetId
                        name
                        code
                        customFields
                    }
                    valueList(options: $options){
                        totalItems
                    }
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                    customFields
                }
                facetId
                name
                code
                translations{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    name
                }
                customFields
            }
            valueList(options: $options1){
                items{
                    id
                    createdAt
                    updatedAt
                    languageCode
                    facet{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                        code
                        customFields
                    }
                    facetId
                    name
                    code
                    translations{
                        id
                        createdAt
                        updatedAt
                        languageCode
                        name
                    }
                    customFields
                }
                totalItems
            }
            customFields
        }
        totalItems
    }
}