query generalSettings{
    generalSettings{
        dateFormat
        description
        email
        language
        startOfWeek
        timeFormat
        timezone
        title
        url
    }
}