query groupTypeTerm($first: Int, $last: Int, $after: String, $before: String, $first1: Int, $last1: Int, $after1: String, $before1: String, $first2: Int, $last2: Int, $after2: String, $before2: String, $first3: Int, $last3: Int, $after3: String, $before3: String, $id: ID!, $idType: GroupTypeTermIdType){
    groupTypeTerm(id: $id, idType: $idType){
        count
        databaseId
        description
        directorySlug
        enqueuedScripts(first: $first, last: $last, after: $after, before: $before){
            edges{
                cursor
                node{
                    after
                    before
                    conditional
                    dependencies{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    extraData
                    group
                    groupLocation
                    handle
                    id
                    src
                    strategy
                    version
                }
            }
            nodes{
                after
                before
                conditional
                dependencies{
                    after
                    before
                    conditional
                    dependencies{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    extraData
                    group
                    groupLocation
                    handle
                    id
                    src
                    strategy
                    version
                }
                extraData
                group
                groupLocation
                handle
                id
                src
                strategy
                version
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        enqueuedStylesheets(first: $first1, last: $last1, after: $after1, before: $before1){
            edges{
                cursor
            }
            nodes{
                after
                before
                conditional
                group
                handle
                id
                isRtl
                media
                path
                rel
                src
                suffix
                title
                version
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        hasDirectory
        id
        isComment
        isContentNode
        isFrontPage
        isPostsPage
        isRestricted
        isTermNode
        link
        name
        pluralName
        showOnGroup
        showOnGroupCreation
        singularName
        slug
        taxonomy{
            cursor
            node{
                connectedContentTypes(first: $first2, last: $last2, after: $after2, before: $before2){
                    edges{
                        cursor
                    }
                    nodes{
                        canExport
                        deleteWithUser
                        description
                        excludeFromSearch
                        graphqlPluralName
                        graphqlSingleName
                        hasArchive
                        hierarchical
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        label
                        menuIcon
                        menuPosition
                        name
                        public
                        publiclyQueryable
                        restBase
                        restControllerClass
                        showInAdminBar
                        showInGraphql
                        showInMenu
                        showInNavMenus
                        showInRest
                        showUi
                        uri
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                connectedTerms(first: $first3, last: $last3, after: $after3, before: $before3){
                    edges{
                        cursor
                    }
                    nodes{
                        count
                        databaseId
                        description
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        link
                        name
                        slug
                        taxonomyName
                        termGroupId
                        termTaxonomyId
                        uri
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                description
                graphqlPluralName
                graphqlSingleName
                hierarchical
                id
                isRestricted
                label
                name
                public
                restBase
                restControllerClass
                showCloud
                showInAdminColumn
                showInGraphql
                showInMenu
                showInNavMenus
                showInQuickEdit
                showInRest
                showUi
            }
        }
        taxonomyName
        termGroupId
        termTaxonomyId
        uri
    }
}