query menuItems($first: Int, $last: Int, $after: String, $before: String, $where: MenuItemToMenuItemConnectionWhereArgs, $first1: Int, $last1: Int, $after1: String, $before1: String, $where1: RootQueryToMenuItemConnectionWhereArgs){
    menuItems(first: $first1, last: $last1, after: $after1, before: $before1, where: $where1){
        edges{
            cursor
            node{
                childItems(first: $first, last: $last, after: $after, before: $before, where: $where){
                    edges{
                        cursor
                    }
                    nodes{
                        cssClasses
                        databaseId
                        description
                        id
                        isRestricted
                        label
                        linkRelationship
                        locations
                        order
                        parentDatabaseId
                        parentId
                        path
                        target
                        title
                        uri
                        url
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                connectedNode{
                    cursor
                    node{
                        databaseId
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isTermNode
                        uri
                    }
                }
                cssClasses
                databaseId
                description
                id
                isRestricted
                label
                linkRelationship
                locations
                menu{
                    cursor
                    node{
                        count
                        databaseId
                        id
                        isRestricted
                        locations
                        name
                        slug
                    }
                }
                order
                parentDatabaseId
                parentId
                path
                target
                title
                uri
                url
            }
        }
        nodes{
            connectedNode{
                cursor
            }
            cssClasses
            databaseId
            description
            id
            isRestricted
            label
            linkRelationship
            locations
            menu{
                cursor
            }
            order
            parentDatabaseId
            parentId
            path
            target
            title
            uri
            url
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}