query menus($first: Int, $last: Int, $after: String, $before: String, $where: MenuToMenuItemConnectionWhereArgs, $first1: Int, $last1: Int, $after1: String, $before1: String, $where1: RootQueryToMenuConnectionWhereArgs){
    menus(first: $first1, last: $last1, after: $after1, before: $before1, where: $where1){
        edges{
            cursor
            node{
                count
                databaseId
                id
                isRestricted
                locations
                menuItems(first: $first, last: $last, after: $after, before: $before, where: $where){
                    edges{
                        cursor
                    }
                    nodes{
                        cssClasses
                        databaseId
                        description
                        id
                        isRestricted
                        label
                        linkRelationship
                        locations
                        order
                        parentDatabaseId
                        parentId
                        path
                        target
                        title
                        uri
                        url
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                name
                slug
            }
        }
        nodes{
            count
            databaseId
            id
            isRestricted
            locations
            name
            slug
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}