query registeredStylesheets($first: Int, $last: Int, $after: String, $before: String){
    registeredStylesheets(first: $first, last: $last, after: $after, before: $before){
        edges{
            cursor
            node{
                after
                before
                conditional
                dependencies{
                    after
                    before
                    conditional
                    dependencies{
                        after
                        before
                        conditional
                        group
                        handle
                        id
                        isRtl
                        media
                        path
                        rel
                        src
                        suffix
                        title
                        version
                    }
                    group
                    handle
                    id
                    isRtl
                    media
                    path
                    rel
                    src
                    suffix
                    title
                    version
                }
                group
                handle
                id
                isRtl
                media
                path
                rel
                src
                suffix
                title
                version
            }
        }
        nodes{
            after
            before
            conditional
            dependencies{
                after
                before
                conditional
                group
                handle
                id
                isRtl
                media
                path
                rel
                src
                suffix
                title
                version
            }
            group
            handle
            id
            isRtl
            media
            path
            rel
            src
            suffix
            title
            version
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}