query registeredScripts($first: Int, $last: Int, $after: String, $before: String){
    registeredScripts(first: $first, last: $last, after: $after, before: $before){
        edges{
            cursor
            node{
                after
                before
                conditional
                dependencies{
                    after
                    before
                    conditional
                    dependencies{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    extraData
                    group
                    groupLocation
                    handle
                    id
                    src
                    strategy
                    version
                }
                extraData
                group
                groupLocation
                handle
                id
                src
                strategy
                version
            }
        }
        nodes{
            after
            before
            conditional
            dependencies{
                after
                before
                conditional
                extraData
                group
                groupLocation
                handle
                id
                src
                strategy
                version
            }
            extraData
            group
            groupLocation
            handle
            id
            src
            strategy
            version
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}