query signups($format: ContentFieldFormatEnum, $format1: ContentFieldFormatEnum, $format2: ContentFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $where: RootQueryToSignupConnectionWhereArgs){
    signups(first: $first, last: $last, after: $after, before: $before, where: $where){
        edges{
            cursor
            node{
                active
                blog{
                    admin{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                    attachmentAvatar{
                        full
                        thumb
                    }
                    attachmentCover{
                        full
                        thumb
                    }
                    databaseId
                    description(format: $format1)
                    domain
                    id
                    isComment
                    isContentNode
                    isFrontPage
                    isPostsPage
                    isTermNode
                    language
                    lastActivity
                    name
                    path
                    public
                    uri
                }
                countSent
                databaseId
                dateSent
                dateSentGmt
                id
                registered
                registeredGmt
                userEmail
                userLogin
                userName
            }
        }
        nodes{
            active
            blog{
                databaseId
                description(format: $format2)
                domain
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isTermNode
                language
                lastActivity
                name
                path
                public
                uri
            }
            countSent
            databaseId
            dateSent
            dateSentGmt
            id
            registered
            registeredGmt
            userEmail
            userLogin
            userName
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}