query taxonomy($first: Int, $last: Int, $after: String, $before: String, $first1: Int, $last1: Int, $after1: String, $before1: String, $where: ContentTypeToContentNodeConnectionWhereArgs, $first2: Int, $last2: Int, $after2: String, $before2: String, $first3: Int, $last3: Int, $after3: String, $before3: String, $first4: Int, $last4: Int, $after4: String, $before4: String, $first5: Int, $last5: Int, $after5: String, $before5: String, $id: ID!, $idType: TaxonomyIdTypeEnum){
    taxonomy(id: $id, idType: $idType){
        connectedContentTypes(first: $first2, last: $last2, after: $after2, before: $before2){
            edges{
                cursor
                node{
                    canExport
                    deleteWithUser
                    description
                    excludeFromSearch
                    graphqlPluralName
                    graphqlSingleName
                    hasArchive
                    hierarchical
                    id
                    isComment
                    isContentNode
                    isFrontPage
                    isPostsPage
                    isRestricted
                    isTermNode
                    label
                    labels{
                        addNew
                        addNewItem
                        allItems
                        archives
                        attributes
                        editItem
                        featuredImage
                        filterItemsList
                        insertIntoItem
                        itemsList
                        itemsListNavigation
                        menuName
                        name
                        newItem
                        notFound
                        notFoundInTrash
                        parentItemColon
                        removeFeaturedImage
                        searchItems
                        setFeaturedImage
                        singularName
                        uploadedToThisItem
                        useFeaturedImage
                        viewItem
                        viewItems
                    }
                    menuIcon
                    menuPosition
                    name
                    public
                    publiclyQueryable
                    restBase
                    restControllerClass
                    showInAdminBar
                    showInGraphql
                    showInMenu
                    showInNavMenus
                    showInRest
                    showUi
                    uri
                }
            }
            nodes{
                canExport
                connectedTaxonomies(first: $first, last: $last, after: $after, before: $before){
                    edges{
                        cursor
                    }
                    nodes{
                        description
                        graphqlPluralName
                        graphqlSingleName
                        hierarchical
                        id
                        isRestricted
                        label
                        name
                        public
                        restBase
                        restControllerClass
                        showCloud
                        showInAdminColumn
                        showInGraphql
                        showInMenu
                        showInNavMenus
                        showInQuickEdit
                        showInRest
                        showUi
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                contentNodes(first: $first1, last: $last1, after: $after1, before: $before1, where: $where){
                    edges{
                        cursor
                    }
                    nodes{
                        contentTypeName
                        databaseId
                        date
                        dateGmt
                        desiredSlug
                        enclosure
                        guid
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isPreview
                        isRestricted
                        isTermNode
                        link
                        modified
                        modifiedGmt
                        previewRevisionDatabaseId
                        previewRevisionId
                        slug
                        status
                        uri
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                deleteWithUser
                description
                excludeFromSearch
                graphqlPluralName
                graphqlSingleName
                hasArchive
                hierarchical
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isRestricted
                isTermNode
                label
                labels{
                    addNew
                    addNewItem
                    allItems
                    archives
                    attributes
                    editItem
                    featuredImage
                    filterItemsList
                    insertIntoItem
                    itemsList
                    itemsListNavigation
                    menuName
                    name
                    newItem
                    notFound
                    notFoundInTrash
                    parentItemColon
                    removeFeaturedImage
                    searchItems
                    setFeaturedImage
                    singularName
                    uploadedToThisItem
                    useFeaturedImage
                    viewItem
                    viewItems
                }
                menuIcon
                menuPosition
                name
                public
                publiclyQueryable
                restBase
                restControllerClass
                showInAdminBar
                showInGraphql
                showInMenu
                showInNavMenus
                showInRest
                showUi
                uri
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        connectedTerms(first: $first5, last: $last5, after: $after5, before: $before5){
            edges{
                cursor
            }
            nodes{
                count
                databaseId
                description
                enqueuedScripts(first: $first3, last: $last3, after: $after3, before: $before3){
                    edges{
                        cursor
                    }
                    nodes{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                enqueuedStylesheets(first: $first4, last: $last4, after: $after4, before: $before4){
                    edges{
                        cursor
                    }
                    nodes{
                        after
                        before
                        conditional
                        group
                        handle
                        id
                        isRtl
                        media
                        path
                        rel
                        src
                        suffix
                        title
                        version
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isRestricted
                isTermNode
                link
                name
                slug
                taxonomyName
                termGroupId
                termTaxonomyId
                uri
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        description
        graphqlPluralName
        graphqlSingleName
        hierarchical
        id
        isRestricted
        label
        name
        public
        restBase
        restControllerClass
        showCloud
        showInAdminColumn
        showInGraphql
        showInMenu
        showInNavMenus
        showInQuickEdit
        showInRest
        showUi
    }
}