query termNode($first: Int, $last: Int, $after: String, $before: String, $first1: Int, $last1: Int, $after1: String, $before1: String, $id: ID!, $idType: TermNodeIdTypeEnum, $taxonomy: TaxonomyEnum){
    termNode(id: $id, idType: $idType, taxonomy: $taxonomy){
        count
        databaseId
        description
        enqueuedScripts(first: $first, last: $last, after: $after, before: $before){
            edges{
                cursor
                node{
                    after
                    before
                    conditional
                    dependencies{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    extraData
                    group
                    groupLocation
                    handle
                    id
                    src
                    strategy
                    version
                }
            }
            nodes{
                after
                before
                conditional
                dependencies{
                    after
                    before
                    conditional
                    dependencies{
                        after
                        before
                        conditional
                        extraData
                        group
                        groupLocation
                        handle
                        id
                        src
                        strategy
                        version
                    }
                    extraData
                    group
                    groupLocation
                    handle
                    id
                    src
                    strategy
                    version
                }
                extraData
                group
                groupLocation
                handle
                id
                src
                strategy
                version
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        enqueuedStylesheets(first: $first1, last: $last1, after: $after1, before: $before1){
            edges{
                cursor
            }
            nodes{
                after
                before
                conditional
                group
                handle
                id
                isRtl
                media
                path
                rel
                src
                suffix
                title
                version
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        id
        isComment
        isContentNode
        isFrontPage
        isPostsPage
        isRestricted
        isTermNode
        link
        name
        slug
        taxonomyName
        termGroupId
        termTaxonomyId
        uri
    }
}