query threads($format: ContentFieldFormatEnum, $format1: ContentFieldFormatEnum, $format2: ContentFieldFormatEnum, $format3: ContentFieldFormatEnum, $format4: ContentFieldFormatEnum, $format5: ContentFieldFormatEnum, $format6: ContentFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $where: ThreadToMessageConnectionWhereArgs, $format7: ContentFieldFormatEnum, $first1: Int, $last1: Int, $after1: String, $before1: String, $where1: ThreadToUserConnectionWhereArgs, $size: Int, $forceDefault: Boolean, $rating: AvatarRatingEnum, $format8: ContentFieldFormatEnum, $format9: ContentFieldFormatEnum, $format10: ContentFieldFormatEnum, $format11: ContentFieldFormatEnum, $format12: ContentFieldFormatEnum, $first2: Int, $last2: Int, $after2: String, $before2: String, $where2: RootQueryToThreadConnectionWhereArgs){
    threads(first: $first2, last: $last2, after: $after2, before: $before2, where: $where2){
        edges{
            cursor
            node{
                databaseId
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isTermNode
                lastMessage{
                    databaseId
                    dateSent
                    dateSentGmt
                    excerpt(format: $format)
                    id
                    isStarred
                    message(format: $format1)
                    sender{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format2)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                    subject(format: $format3)
                    threadId
                }
                messages(first: $first, last: $last, after: $after, before: $before, where: $where){
                    edges{
                        cursor
                    }
                    nodes{
                        databaseId
                        dateSent
                        dateSentGmt
                        excerpt(format: $format4)
                        id
                        isStarred
                        message(format: $format5)
                        subject(format: $format6)
                        threadId
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                recipients(first: $first1, last: $last1, after: $after1, before: $before1, where: $where1){
                    edges{
                        cursor
                    }
                    nodes{
                        capKey
                        capabilities
                        databaseId
                        description
                        email
                        extraCapabilities
                        firstName
                        id
                        isComment
                        isContentNode
                        isFrontPage
                        isPostsPage
                        isRestricted
                        isTermNode
                        lastName
                        latestUpdate(format: $format7)
                        link
                        locale
                        memberTypes
                        mentionName
                        name
                        nicename
                        nickname
                        registeredDate
                        shouldShowAdminToolbar
                        slug
                        totalFriendCount
                        totalMessagesUnreadCount
                        uri
                        url
                        username
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                senders{
                    attachmentAvatar{
                        full
                        thumb
                    }
                    attachmentCover{
                        full
                        thumb
                    }
                    avatar(size: $size, forceDefault: $forceDefault, rating: $rating){
                        default
                        extraAttr
                        forceDefault
                        foundAvatar
                        height
                        isRestricted
                        rating
                        scheme
                        size
                        url
                        width
                    }
                    capKey
                    capabilities
                    databaseId
                    description
                    email
                    extraCapabilities
                    firstName
                    id
                    isComment
                    isContentNode
                    isFrontPage
                    isPostsPage
                    isRestricted
                    isTermNode
                    lastName
                    latestUpdate(format: $format8)
                    link
                    locale
                    memberTypes
                    mentionName
                    name
                    nicename
                    nickname
                    registeredDate
                    shouldShowAdminToolbar
                    slug
                    totalFriendCount
                    totalMessagesUnreadCount
                    uri
                    url
                    username
                }
                unreadCount
                uri
            }
        }
        nodes{
            databaseId
            id
            isComment
            isContentNode
            isFrontPage
            isPostsPage
            isTermNode
            lastMessage{
                databaseId
                dateSent
                dateSentGmt
                excerpt(format: $format9)
                id
                isStarred
                message(format: $format10)
                subject(format: $format11)
                threadId
            }
            senders{
                capKey
                capabilities
                databaseId
                description
                email
                extraCapabilities
                firstName
                id
                isComment
                isContentNode
                isFrontPage
                isPostsPage
                isRestricted
                isTermNode
                lastName
                latestUpdate(format: $format12)
                link
                locale
                memberTypes
                mentionName
                name
                nicename
                nickname
                registeredDate
                shouldShowAdminToolbar
                slug
                totalFriendCount
                totalMessagesUnreadCount
                uri
                url
                username
            }
            unreadCount
            uri
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}