query userRoles($first: Int, $last: Int, $after: String, $before: String){
    userRoles(first: $first, last: $last, after: $after, before: $before){
        edges{
            cursor
            node{
                capabilities
                displayName
                id
                isRestricted
                name
            }
        }
        nodes{
            capabilities
            displayName
            id
            isRestricted
            name
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}