query xprofileGroups($format: ContentFieldFormatEnum, $format1: ContentFieldFormatEnum, $first: Int, $last: Int, $after: String, $before: String, $where: XProfileGroupToXProfileFieldConnectionWhereArgs, $format2: ContentFieldFormatEnum, $first1: Int, $last1: Int, $after1: String, $before1: String, $where1: RootQueryToXProfileGroupConnectionWhereArgs){
    xprofileGroups(first: $first1, last: $last1, after: $after1, before: $before1, where: $where1){
        edges{
            cursor
            node{
                canDelete
                databaseId
                description(format: $format)
                fields(first: $first, last: $last, after: $after, before: $before, where: $where){
                    edges{
                        cursor
                    }
                    nodes{
                        canDelete
                        databaseId
                        description(format: $format1)
                        doAutolink
                        fieldOrder
                        groupId
                        id
                        isDefaultOption
                        isRequired
                        memberTypes
                        name
                        optionOrder
                        orderBy
                        type
                        visibilityLevel
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                }
                groupOrder
                id
                name
            }
        }
        nodes{
            canDelete
            databaseId
            description(format: $format2)
            groupOrder
            id
            name
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}